* planet-git

  This is the stub README.org for the "planet-git" project.  The whole
  project could be described as a stub.  There is still much work to do.
  Be aware this is the first project I ever done with Common Lisp, so if
  your eyes begin to bleed it's not my fault. You have been warned.

** Installation

   Currently this application isn't ready for any kind of real
   deployment.  So there will only be configuration instructions until
   this changes.

*** Prerequisites

    The following configuration on Linux (Ubuntu Oneiric Ocelot) is
    known to work:

    - PostgreSQL (tested with version 9.1.3)
    - SBCL 1.0.56 (sbcl-1.0.56.55-b06f72f-linux-x86)
    - cl-git (git repo 2012-05-02)
    - Hunchentoot (1.1.0)
    - Postmodern (darcs repo)

*** Configuration

    Configuration options are defined in a file called config.sexp. A
    template is provided in config.sexp.in. Please copy that file to a
    new file config.sexp and adapt the values to your settings.

**** Create a PostgreSQL database

     You have to create an empty PostgreSQL database before running
     planet-git for the first time. On most Linux distros, there is a
     user postgres, who is privileged to create users and databases:

     #+BEGIN_EXAMPLE
     sudo su - postgres
     createuser gitui -P
     createdb -O gitui -E UTF-8 planet_git
     #+END_EXAMPLE

*** Git Hook

    The git-shell.lisp script wraps the git shell command and records
    the git events.  It needs to be added to the .ssh/authorized_keys
    of the git user.  This will need to be done manually until this is
    correctly implemented.

    command="KEY_ID=4
    ./git-shell.lisp",no-port-forwarding,no-agent-forwarding,no-X11-forwarding,no-pty
    ssh-rsa AAAAB... russell@marvin

** JSON REST Interface

   the basic interface should return packets like this, where next and
   previous should be the urls to get the next and previous results.

   #+BEGIN_EXAMPLE
   {
     "count": 1,
     "next": null,
     "previous": null,
     "results": [{"username": "russell",
                  "fullname": "Russell Sim",
                  "location": "null",
                  "photo": "https:\/\/secure.gravatar.com\/avatar\/9f656c1da1eef46c4f8384725234f557?s=80"}
                ]
   }
   #+END_EXAMPLE

** Developing

   To start hacking on planet-git, make sure the dependencies which
   are declared in the ASDF file are loadable by ASDF. With the
   correct configuration (cf. above), you should be able to start and
   stop the server with:

   #+BEGIN_SRC common-lisp
   (asdf:oos 'asdf:load-op :planet-git)
   (planet-git:startup)

   ; ...

   (planet-git:shutdown)
   #+END_SRC


*** Local Development Deployment
    Add a git user,

    #+BEGIN_SRC shell
    adduser git
    #+END_SRC

    Now as the git user install quicklisp and link in the development
    version.

    #+BEGIN_SRC shell
    curl -O http://beta.quicklisp.org/quicklisp.lisp
    sbcl --load quicklisp.lisp
    #+END_SRC

    Quicklisp needs to be installed into ~/.quicklisp so that there
    won't be any problems if a user is created with the name
    Quicklisp.

    #+BEGIN_SRC common-lisp
    (quicklisp-quickstart:install :path ".quicklisp/")
    (quit)
    #+END_SRC

    Now development a development copy of planet-git is linked in for
    ASDF to find.

    #+BEGIN_SRC shell
    mkdir -p ~/.local/share/common-lisp/source/
    cd ~/.local/share/common-lisp/source/
    ln -s ~user/projects/planet-git .
    cd -
    #+END_SRC
*** Debugging

    (setf hunchentoot:*catch-errors-p* nil)

*** Definitions

    Pages, return complete html pages
    Views are view controllers
    Fragments, return html fragments, parts of pages
